### ISSUE TITLE
Find a fil?

### ISSUE THREAD

**Issue by daybarr** [linssen/better_than_predator#35]
![screenshot_20171004-212014](https://user-images.githubusercontent.com/140142/31198827-7d96b8bc-a94d-11e7-9e8a-6c12d6c4b1e1.png)

**Comment by daybarr** [comment]
That previous screenshot from Brave browser on a Nexus 5X with Android 8.0.0. Same problem with Chrome

![screenshot_20171004-214855](https://user-images.githubusercontent.com/140142/31198980-f6f4427e-a94d-11e7-81ff-06aec89a642e.png)

**Comment by linssen** [comment]
![](https://media.giphy.com/media/qz2ahoDyseZGg/giphy.gif)
Rest assured, it'll be fixed in the upcoming Vue.js rewrite.

**Comment by linssen** [comment]
Fixed in #38

**Comment by daybarr** [comment]
Wooooooo
